;-------------------------------------------------------------------------------
; 老化测试模块配置示例
;
; [example]
; activated = 1
;
;
; activated
;   0: 不测试该模块
;   1: 测试该模块
;-------------------------------------------------------------------------------
[cpu]
activated = 1

;-------------------------------------------------------------------------------
; mem_size
;   The size of memory to test. unit: MB
; mem_time
;   The time of memory to test. unit: second
; mem_loop
;   whether or not to loop test.
;-------------------------------------------------------------------------------
[memory]
activated = 1
mem_size  = 64
mem_time  = 120
threads   = 1
mem_loop  = 1

[gpu]
activated = 1

[vpu]
activated = 1
testvideo_sys = /system/usr/Aging_Test_Video.mp4
testvideo = /sdcard/Aging_Test_Video.mp4
activated_float = 1
floatvideo_sys = /system/usr/Aging_Test_Video_Float.mp4
floatvideo = /sdcard/Aging_Test_Video_Float.mp4

[usbhost]
activated = 0

[ethernet]
activated = 0
eth0_ping_ipaddress = 8.8.8.8
eth1_ping_ipaddress = 8.8.8.8

[thermal]
activated = 0

[busmon]
activated = 0
