LOCAL_PATH := $(call my-dir)

#
# SECTION 1: BUILD_PREBUILT for librockit
#

include $(CLEAR_VARS)
LOCAL_MODULE := librockit
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES :=lib/arm/media_core/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

#
# SECTION 2: BUILD_PREBUILT for libffmpeg
#

include $(CLEAR_VARS)
LOCAL_MODULE := libffmpeg_58
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES :=lib/arm/media_core/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

#
# SECTION 3: BUILD_PREBUILT for libjpeghwenc
#

include $(CLEAR_VARS)
LOCAL_MODULE := libjpeghwenc
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
ifneq ($(strip $(TARGET_2ND_ARCH)), )
    LOCAL_MULTILIB := both
    LOCAL_SRC_FILES_$(TARGET_ARCH) := lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    LOCAL_SRC_FILES_$(TARGET_2ND_ARCH) := lib/$(TARGET_2ND_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
else
    ifneq ($(filter rk3326, $(strip $(TARGET_BOARD_PLATFORM))), )
        LOCAL_SRC_FILES :=lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    endif
endif
include $(BUILD_PREBUILT)

#
# SECTION 4: BUILD_PREBUILT for libmpp
#

include $(CLEAR_VARS)
LOCAL_MODULE := libmpp
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 32
ifneq ($(strip $(TARGET_2ND_ARCH)), )
    LOCAL_MULTILIB := both
    LOCAL_SRC_FILES_$(TARGET_ARCH) := lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    LOCAL_SRC_FILES_$(TARGET_2ND_ARCH) := lib/$(TARGET_2ND_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
else
    ifneq ($(filter rk3326, $(strip $(TARGET_BOARD_PLATFORM))), )
        LOCAL_SRC_FILES :=lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    endif
endif
include $(BUILD_PREBUILT)

#
# SECTION 5: BUILD_PREBUILT for libvpu
#

include $(CLEAR_VARS)
LOCAL_MODULE := libvpu
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 32
ifneq ($(strip $(TARGET_2ND_ARCH)), )
    LOCAL_MULTILIB := both
    LOCAL_SRC_FILES_$(TARGET_ARCH) := lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    LOCAL_SRC_FILES_$(TARGET_2ND_ARCH) := lib/$(TARGET_2ND_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
else
    ifneq ($(filter rk3326, $(strip $(TARGET_BOARD_PLATFORM))), )
        LOCAL_SRC_FILES :=lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    endif
endif
include $(BUILD_PREBUILT)

#
# SECTION 6: BUILD_PREBUILT for librk_vpuapi
#

include $(CLEAR_VARS)
LOCAL_MODULE := librk_vpuapi
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := 32
ifneq ($(strip $(TARGET_2ND_ARCH)), )
    LOCAL_MULTILIB := both
    LOCAL_SRC_FILES_$(TARGET_ARCH) := lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    LOCAL_SRC_FILES_$(TARGET_2ND_ARCH) := lib/$(TARGET_2ND_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
else
    ifneq ($(filter rk3326, $(strip $(TARGET_BOARD_PLATFORM))), )
        LOCAL_SRC_FILES :=lib/$(TARGET_ARCH)/media_core/mpp_dev/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
    endif
endif
include $(BUILD_PREBUILT)
